services:
  postgres:
    image: postgres:16-alpine
    container_name: gastroflow-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gastroflow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
    container_name: gastroflow-backend
    environment:
      NODE_ENV: production
      PORT: 5001
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/gastroflow
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5001:5001"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: /api
    container_name: gastroflow-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  pgdata:
